### ISSUE TITLE
Move documentation to e2immu-site automatically

### ISSUE THREAD

**Issue by satyamkapoor** [e2immu/e2immu-documentation#1]
Documentation of e2immu sits in e2immu-site project's static directory. It'll be great to have a workflow which builds and moves this documentation to the respective folder.

**Comment by bnaudts** [comment]
OK I should have tried it before accepting ... I added a GTOKEN, and touched a directory static/docs (the first run complained that wasn't present) but then, it only copies the images/ directory, and not the html files. The cp -r commands looks good and the gradle command runs green, still there are no files. Please debug :-)

**Comment by bnaudts** [comment]
I've given it one attempt (see logs of the action) but that was not successful.

* Maybe asciidoctor doesn't produce enough because some ruby modules have not been loaded? I'm using a particular source code highlighter: `:source-highlighter: coderay`

* another issue is that when nothing changes output-wise, as in the latest run, then the git command fails. That shouldn't happen I guess

**Comment by satyamkapoor** [comment]
I checked the html generated using asciidoc gradle has correct syntax highlighting. Files were not being moved to e2immu-site because of rules in .gitignore in e2immu-site which I updated and submitted a new PR.

Regarding the git command, I witnessed whenever gradle asciidoc task is run, it updates the timestamp in generated html docs so there always is a change when we do a git status. I don't think we need to handle this status check then. Shouldn't be a blocker.
